---
title: "Ring Offset Color"
description: "Utilities for setting the color of outline ring offsets."
---

import plugin from 'tailwindcss/lib/plugins/ringOffsetColor'
import { Variants } from '@/components/Variants'
import { Disabling } from '@/components/Disabling'

export const classes = {
  plugin,
  transformProperties: ({ selector, properties }) => {
    properties['box-shadow'] = `0 0 0 var(--tw-ring-offset-width) var(--tw-ring-offset-color), var(--tw-ring-shadow)`
    return properties
  }
}


## Usage

Use the `ring-offset-{color}` utilities to change the color of a ring offset. Usually this is done to try and match the offset to the parent background color, since true box-shadow offsets aren't actually possible in CSS.

```html violet
<template preview class="p-0">
  <div class="bg-violet-100 grid grid-cols-1 gap-6 justify-items-center p-8 ">
    <p class="font-semibold text-violet-600">bg-purple-100</p>
    <button tabindex="-1" class="focus:outline-none text-sm px-5 py-3 rounded-md font-semibold text-white bg-violet-500 ring ring-violet-600 ring-offset-4 ring-offset-violet-100">
      ring-offset-purple-100
    </button>
  </div>
</template>

<div class="... **bg-purple-100**">
  <button class="... ring ring-purple-600 **ring-offset-4** **ring-offset-purple-100**">
    ring-offset-purple-100
  </button>
</div>
```

---


## Responsive

To control the ring offset color at a specific breakpoint, add a `{screen}:` prefix to any existing ring offset color utility. For example, use `md:ring-offset-blue-500` to apply the `ring-offset-blue-500` utility at only medium screen sizes and above.

```html
<button class="ring-2 ring-offset-2 ring-offset-blue-300 **md:ring-offset-blue-500**">
  <!-- ... -->
</button>
```

For more information about Tailwind's responsive design features, check out the [Responsive Design](/docs/responsive-design) documentation.

---

## Customizing

You can customize which ring offset color utilities are generated by customizing your color palette under the `colors` key in the `theme` section of your `tailwind.config.js` file:

```js
// tailwind.config.js
const colors = require('tailwindcss/colors')

module.exports = {
  theme: {
    colors: {
      gray: colors.blueGray,
      indigo: colors.indigo,
      red: colors.rose,
      yellow: colors.yellow,
    }
  }
}
```

If you'd like to customize only the ring offset color utilities without affecting your global color palette, use the `ringOffsetColor` key instead:

```js
// tailwind.config.js
const colors = require('tailwindcss/colors')

module.exports = {
  theme: {
    ringOffsetColor: {
      white: colors.white,
      pink: colors.fuchsia,
    }
  }
}
```

Learn more about customizing the default theme in the [theme customization documentation](/docs/theme#customizing-the-default-theme).

### Variants

<Variants plugin="ringOffsetColor" />

### Disabling

<Disabling plugin="ringOffsetColor" />
