<?php

return [
    'Getting Started' => [
        'Quick Start' => 'quick-start',
        'Installation' => 'installation',
        'Upgrade Guide' => 'upgrading-to-v1',
        'Using with Sass/Less/Stylus' => 'using-with-sass-less-stylus',
        'Controlling File Size' => 'controlling-file-size',
        'Browser Support' => 'browser-support',
    ],
    'Core Concepts' => [
        'Utility-First' => 'utility-first',
        'Responsive Design' => 'responsive-design',
        'State Variants' => 'state-variants',
        'Adding New Utilities' => 'adding-new-utilities',
        'Extracting Components' => 'extracting-components',
        'Adding Base Styles' => 'adding-base-styles',
        'Functions &amp; Directives' => 'functions-and-directives',
    ],
    'Customizing' => [
        'Configuration' => 'configuration',
        'Theme' => 'theme',
        'Colors' => 'colors',
        'Spacing' => 'spacing',
        'Breakpoints' => 'breakpoints',
        'Variants' => 'configuring-variants',
        'Plugins' => 'plugins',
    ],
    'Layout' => [
        'Container' => 'container',
        'Display' => 'display',
        'Float' => 'float',
        'Object Fit' => 'object-fit',
        'Object Position' => 'object-position',
        'Overflow' => 'overflow',
        'Position' => 'position',
        'Top / Right / Bottom / Left' => 'top-right-bottom-left',
        'Visibility' => 'visibility',
        'Z-Index' => 'z-index',
    ],
    'Typography' => [
        'Color' => 'text-color',
        'Font Family' => 'font-family',
        'Font Size' => 'font-size',
        'Font Weight' => 'font-weight',
        'Letter Spacing' => 'letter-spacing',
        'Line Height' => 'line-height',
        'List Style Type' => 'list-style-type',
        'List Style Position' => 'list-style-position',
        'Style &amp; Decoration' => 'text-style',
        'Text Align' => 'text-align',
        'Vertical Align' => 'vertical-align',
        'Whitespace' => 'whitespace',
        'Word Break' => 'word-break',
    ],
    'Backgrounds' => [
        'Background Attachment' => 'background-attachment',
        'Background Color' => 'background-color',
        'Background Position' => 'background-position',
        'Background Repeat' => 'background-repeat',
        'Background Size' => 'background-size',
    ],
    'Borders' => [
        'Border Color' => 'border-color',
        'Border Style' => 'border-style',
        'Border Width' => 'border-width',
        'Border Radius' => 'border-radius',
    ],
    'Flexbox' => [
        'Flex Direction' => 'flex-direction',
        'Flex Wrapping' => 'flex-wrap',
        'Align Items' => 'align-items',
        'Align Content' => 'align-content',
        'Align Self' => 'align-self',
        'Justify Content' => 'justify-content',
        'Flex' => 'flex',
        'Flex Grow' => 'flex-grow',
        'Flex Shrink' => 'flex-shrink',
    ],
    'Spacing' => [
        'Padding' => 'padding',
        'Margin' => 'margin',
        'Negative Margin' => 'negative-margin',
    ],
    'Sizing' => [
        'Width' => 'width',
        'Min-Width' => 'min-width',
        'Max-Width' => 'max-width',
        'Height' => 'height',
        'Min-Height' => 'min-height',
        'Max-Height' => 'max-height',
    ],
    'Tables' => [
        'Border Collapse' => 'border-collapse',
        'Table Layout' => 'table-layout',
    ],
    'Effects' => [
        'Box Shadow' => 'box-shadow',
        'Opacity' => 'opacity',
    ],
    'Interactivity' => [
        'Appearance' => 'appearance',
        'Cursor' => 'cursor',
        'Outline' => 'outline',
        'Pointer Events' => 'pointer-events',
        'Resize' => 'resize',
        'User Select' => 'user-select',
    ],
    'SVG' => [
        'Fill' => 'fill',
        'Stroke' => 'stroke',
    ],
    'Component Examples' => [
        'Alerts' => 'examples/alerts',
        'Buttons' => 'examples/buttons',
        'Cards' => 'examples/cards',
        'Forms' => 'examples/forms',
        'Grids' => 'examples/grids',
        'Navigation' => 'examples/navigation',
    ],
];
