<?php

return [
    'Introduction' => [
        'What is Tailwind?' => 'what-is-tailwind',
    ],
    'Getting Started' => [
        'Installation' => 'installation',
        'Configuration' => 'configuration',
        'Colors' => 'colors',
        'Responsive Design' => 'responsive-design',
        'State Variants' => 'state-variants',
        'Adding New Utilities' => 'adding-new-utilities',
        'Extracting Components' => 'extracting-components',
        'Functions &amp; Directives' => 'functions-and-directives',
        'Controlling File Size' => 'controlling-file-size',
        'Plugins' => 'plugins',
    ],
    'Layout' => [
        'Container' => 'container',
        'Display' => 'display',
        'Floats' => 'floats',
        'Overflow' => 'overflow',
        'Position' => 'positioning',
        'Visibility' => 'visibility',
        'Z-Index' => 'z-index',
    ],
    'Typography' => [
        'Color' => 'text-color',
        'Font Family' => 'fonts',
        'Font Size' => 'text-sizing',
        'Font Weight' => 'font-weight',
        'Letter Spacing' => 'letter-spacing',
        'Line Height' => 'line-height',
        'Lists' => 'lists',
        'Style &amp; Decoration' => 'text-style',
        'Text Alignment' => 'text-alignment',
        'Vertical Alignment' => 'vertical-alignment',
        'Whitespace &amp; Wrapping' => 'whitespace-and-wrapping',
    ],
    'Backgrounds' => [
        'Background Attachment' => 'background-attachment',
        'Background Color' => 'background-color',
        'Background Position' => 'background-position',
        'Background Repeat' => 'background-repeat',
        'Background Size' => 'background-size',
    ],
    'Borders' => [
        'Border Color' => 'border-color',
        'Border Style' => 'border-style',
        'Border Width' => 'border-width',
        'Border Radius' => 'border-radius',
    ],
    'Flexbox' => [
        'Display' => 'flexbox-display',
        'Flex Direction' => 'flexbox-direction',
        'Flex Wrapping' => 'flexbox-wrapping',
        'Align Items' => 'flexbox-align-items',
        'Align Content' => 'flexbox-align-content',
        'Align Self' => 'flexbox-align-self',
        'Justify Content' => 'flexbox-justify-content',
        'Flex, Grow, &amp; Shrink' => 'flexbox-flex-grow-shrink',
    ],
    'Spacing' => [
        'Margin &amp; Padding' => 'spacing',
    ],
    'Sizing' => [
        'Width' => 'width',
        'Min-Width' => 'min-width',
        'Max-Width' => 'max-width',
        'Height' => 'height',
        'Min-Height' => 'min-height',
        'Max-Height' => 'max-height',
    ],
    'Interactivity' => [
        'Cursor' => 'cursor',
        'Pointer Events' => 'pointer-events',
        'Resize' => 'resize',
        'User Select' => 'user-select',
    ],
    'Miscellaneous' => [
        'Appearance' => 'appearance',
        'Box Shadow' => 'shadows',
        'Opacity' => 'opacity',
        'SVG' => 'svg',
    ],
    'Component Examples' => [
        'Alerts' => 'examples/alerts',
        'Buttons' => 'examples/buttons',
        'Cards' => 'examples/cards',
        'Forms' => 'examples/forms',
        'Grids' => 'examples/grids',
        'Navigation' => 'examples/navigation',
    ],
];
