<?php

return [
    'Documentation' => [
        'Getting Started' => [
            'Installation' => '/docs/installation',
            'Release Notes' => '/docs/release-notes',
            'Upgrade Guide' => '/docs/upgrading-to-v1',
            'Using with Preprocessors' => '/docs/using-with-preprocessors',
            'Controlling File Size' => '/docs/controlling-file-size',
            'Browser Support' => '/docs/browser-support',
            'IntelliSense' => '/docs/intellisense',
        ],
        'Core Concepts' => [
            'Utility-First' => '/docs/utility-first',
            'Responsive Design' => '/docs/responsive-design',
            'Pseudo-Class Variants' => '/docs/pseudo-class-variants',
            'Adding Base Styles' => '/docs/adding-base-styles',
            'Extracting Components' => '/docs/extracting-components',
            'Adding New Utilities' => '/docs/adding-new-utilities',
            'Functions & Directives' => '/docs/functions-and-directives',
        ],
        'Customization' => [
            'Configuration' => '/docs/configuration',
            'Theme' => '/docs/theme',
            'Breakpoints' => '/docs/breakpoints',
            'Colors' => '/docs/customizing-colors',
            'Spacing' => '/docs/customizing-spacing',
            'Variants' => '/docs/configuring-variants',
            'Writing Plugins' => '/docs/plugins',
        ],
        'Base styles' => [
            'Preflight' => '/docs/preflight',
        ],
        'Layout' => [
            'Container' => '/docs/container',
            'Box Sizing' => '/docs/box-sizing',
            'Display' => '/docs/display',
            'Float' => '/docs/float',
            'Clear' => '/docs/clear',
            'Object Fit' => '/docs/object-fit',
            'Object Position' => '/docs/object-position',
            'Overflow' => '/docs/overflow',
            'Position' => '/docs/position',
            'Top / Right / Bottom / Left' => '/docs/top-right-bottom-left',
            'Visibility' => '/docs/visibility',
            'Z-Index' => '/docs/z-index',
        ],
        'Flexbox' => [
            'Flex Direction' => '/docs/flex-direction',
            'Flex Wrap' => '/docs/flex-wrap',
            'Align Items' => '/docs/align-items',
            'Align Content' => '/docs/align-content',
            'Align Self' => '/docs/align-self',
            'Justify Content' => '/docs/justify-content',
            'Flex' => '/docs/flex',
            'Flex Grow' => '/docs/flex-grow',
            'Flex Shrink' => '/docs/flex-shrink',
            'Order' => '/docs/order',
        ],
        'Grid' => [
            'Grid Template Columns' => '/docs/grid-template-columns',
            'Grid Column Start / End' => '/docs/grid-column',
            'Grid Template Rows' => '/docs/grid-template-rows',
            'Grid Row Start / End' => '/docs/grid-row',
            'Gap' => '/docs/gap',
            'Grid Auto Flow' => '/docs/grid-auto-flow',
        ],
        'Spacing' => [
            'Padding' => '/docs/padding',
            'Margin' => '/docs/margin',
            'Space Between' => '/docs/space',
        ],
        'Sizing' => [
            'Width' => '/docs/width',
            'Min-Width' => '/docs/min-width',
            'Max-Width' => '/docs/max-width',
            'Height' => '/docs/height',
            'Min-Height' => '/docs/min-height',
            'Max-Height' => '/docs/max-height',
        ],
        'Typography' => [
            'Font Family' => '/docs/font-family',
            'Font Size' => '/docs/font-size',
            'Font Smoothing' => '/docs/font-smoothing',
            'Font Style' => '/docs/font-style',
            'Font Weight' => '/docs/font-weight',
            'Letter Spacing' => '/docs/letter-spacing',
            'Line Height' => '/docs/line-height',
            'List Style Type' => '/docs/list-style-type',
            'List Style Position' => '/docs/list-style-position',
            'Placeholder Color' => '/docs/placeholder-color',
            'Placeholder Opacity' => '/docs/placeholder-opacity',
            'Text Align' => '/docs/text-align',
            'Text Color' => '/docs/text-color',
            'Text Opacity' => '/docs/text-opacity',
            'Text Decoration' => '/docs/text-decoration',
            'Text Transform' => '/docs/text-transform',
            'Vertical Align' => '/docs/vertical-align',
            'Whitespace' => '/docs/whitespace',
            'Word Break' => '/docs/word-break',
        ],
        'Backgrounds' => [
            'Background Attachment' => '/docs/background-attachment',
            'Background Color' => '/docs/background-color',
            'Background Opacity' => '/docs/background-opacity',
            'Background Position' => '/docs/background-position',
            'Background Repeat' => '/docs/background-repeat',
            'Background Size' => '/docs/background-size',
        ],
        'Borders' => [
            'Border Radius' => '/docs/border-radius',
            'Border Width' => '/docs/border-width',
            'Border Color' => '/docs/border-color',
            'Border Opacity' => '/docs/border-opacity',
            'Border Style' => '/docs/border-style',
            'Divide Width' => '/docs/divide-width',
            'Divide Color' => '/docs/divide-color',
            'Divide Opacity' => '/docs/divide-opacity',
        ],
        'Tables' => [
            'Border Collapse' => '/docs/border-collapse',
            'Table Layout' => '/docs/table-layout',
        ],
        'Effects' => [
            'Box Shadow' => '/docs/box-shadow',
            'Opacity' => '/docs/opacity',
        ],
        'Transitions and Animation' => [
            'Transition Property' => '/docs/transition-property',
            'Transition Duration' => '/docs/transition-duration',
            'Transition Timing Function' => '/docs/transition-timing-function',
            'Transition Delay' => '/docs/transition-delay',
            'Animation' => '/docs/animation',
        ],
        'Transforms' => [
            'Scale' => '/docs/scale',
            'Rotate' => '/docs/rotate',
            'Translate' => '/docs/translate',
            'Rotate' => '/docs/rotate',
            'Skew' => '/docs/skew',
            'Transform Origin' => '/docs/transform-origin',
        ],
        'Interactivity' => [
            'Appearance' => '/docs/appearance',
            'Cursor' => '/docs/cursor',
            'Outline' => '/docs/outline',
            'Pointer Events' => '/docs/pointer-events',
            'Resize' => '/docs/resize',
            'User Select' => '/docs/user-select',
        ],
        'SVG' => [
            'Fill' => '/docs/fill',
            'Stroke' => '/docs/stroke',
            'Stroke Width' => '/docs/stroke-width',
        ],
        'Accessibility' => [
            'Screen Readers' => '/docs/screen-readers',
        ],
        'Official Plugins' => [
            'Typography' => '/docs/typography-plugin',
        ],
    ],
    'Components' => [
        'Examples' => [
            'Alerts' => '/components/alerts',
            'Buttons' => '/components/buttons',
            'Cards' => '/components/cards',
            'Forms' => '/components/forms',
            'Flexbox Grids' => '/components/flexbox-grids',
            'Navigation' => '/components/navigation',
        ],
    ],
    'Screencasts' => [
        'Getting Up and Running' => [
            'Setting Up Tailwind and PostCSS' => '/course/setting-up-tailwind-and-postcss',
            'The Utility-First Workflow' => '/course/the-utility-first-workflow',
            'Responsive Design' => '/course/responsive-design',
            'Hover, Focus, and Active Styles' => '/course/hover-focus-and-active-styles',
            'Composing Utilities with @apply' => '/course/composing-utilities-with-apply',
            'Extracting Reusable Components' => '/course/extracting-reusable-components',
            'Customizing Your Design System' => '/course/customizing-your-design-system',
            'Optimizing for Production' => '/course/optimizing-for-production',
        ],
        'Designing an image card' => [
            'Structuring a Basic Card' => '/course/structuring-a-basic-card',
            'Making Text Content Feel Designed' => '/course/making-text-content-feel-designed',
            'Working with SVG Icons' => '/course/working-with-svg-icons',
            'Designing a Badge' => '/course/designing-a-badge',
            'Cropping and Positioning Images' => '/course/cropping-and-positioning-images',
            'Locking Images to a Fixed Aspect Ratio' => '/course/locking-images-to-a-fixed-aspect-ratio',
            'Creating Depth with Shadows and Layers' => '/course/creating-depth-with-shadows-and-layers',
        ],
        'Building a responsive navbar' => [
            'Building a Navbar Layout with Flexbox' => '/course/building-a-navbar-layout-with-flexbox',
            'Toggling the Navbar Links on Mobile' => '/course/toggling-the-navbar-links-on-mobile',
            'Making the Navbar Responsive' => '/course/making-the-navbar-responsive',
        ],
        'Building a dropdown menu' => [
            'Styling the Basic Dropdown Elements' => '/course/styling-the-basic-dropdown-elements',
            'Positioning the Dropdown Area' => '/course/positioning-the-dropdown-area',
            'Making the Dropdown Interactive' => '/course/making-the-dropdown-interactive',
            'Adapting the Dropdown for Mobile' => '/course/adapting-the-dropdown-for-mobile',
        ],
        'Styling form elements' => [
            'Styling basic text inputs' => '/course/coming-soon',
            'Using positioning to build a search input group' => '/course/coming-soon',
            'Using focus-within to change the search icon color' => '/course/coming-soon',
            'Styling custom select menus' => '/course/coming-soon',
            'Styling custom checkboxes and radio buttons' => '/course/coming-soon',
            'Using the custom forms plugin' => '/course/coming-soon',
        ],
        'Working with CMS content' => [
            'Targeting elements when you can\'t add classes' => '/course/coming-soon',
            'Styling headings' => '/course/coming-soon',
            'Styling paragraph text' => '/course/coming-soon',
            'Styling lists' => '/course/coming-soon',
        ],
        'Layout Patterns' => [
            'Building a responsive sidebar layout with flexbox' => '/course/coming-soon',
            'Building responsive grids' => '/course/coming-soon',
            'Building a sticky footer' => '/course/coming-soon',
            'Building a side-scrolling card layout' => '/course/coming-soon',
        ],
        'Extending Tailwind' => [
            'Using custom fonts'  => '/course/coming-soon',
            'Using a custom color palette'  => '/course/coming-soon',
            'Adding custom utilities'  => '/course/coming-soon',
            'Working with third-party plugins'  => '/course/coming-soon',
            'Writing your own simple plugin'  => '/course/coming-soon',
        ]
    ],
    'Resources' => [
        'On this page' => [
            'Learning design' => '#learning-design',
            'Images and illustrations' => '#images-and-illustrations',
            'Icons' => '#icons',
            'Background patterns' => '#background-patterns',
        ]
    ],
    'Community' => [
        'On this page' => [
            'Discord' => '#discord',
            'Forum' => '#forum',
            'GitHub' => '#github',
            'Twitter' => '#twitter',
        ]
    ],
];
