packages:
  - 'crates/node'
  - 'crates/node/npm/*'
  - 'packages/*'
  - 'playgrounds/*'
  - 'integrations'

allowBuilds:
  '@parcel/watcher': true
  bun: true
  esbuild: true
  sharp: false
  tree-sitter: true
  tree-sitter-javascript: true
  tree-sitter-typescript: true

catalog:
  '@types/node': 22.19.19
  dedent: 1.7.2
  enhanced-resolve: 5.21.6
  lightningcss-darwin-arm64: 1.32.0
  lightningcss-darwin-x64: 1.32.0
  lightningcss-linux-arm64-gnu: 1.32.0
  lightningcss-linux-arm64-musl: 1.32.0
  lightningcss-linux-x64-gnu: 1.32.0
  lightningcss-linux-x64-musl: 1.32.0
  lightningcss-win32-x64-msvc: 1.32.0
  lightningcss: 1.32.0
  postcss: 8.5.15
  prettier: 3.8.3
  vite: 8.0.14
  webpack: 5.107.0

patchedDependencies:
  '@parcel/watcher@2.5.1': patches/@parcel__watcher@2.5.1.patch
  lightningcss@1.32.0: patches/lightningcss@1.32.0.patch

# TODO: Scope this just for the oxide-wasm32-wasi package
nodeLinker: hoisted
# packageConfigs:
#   '@tailwindcss/oxide-wasm32-wasi':
#     nodeLinker: hoisted
