packages:
  - 'crates/node'
  - 'crates/node/npm/*'
  - 'packages/*'
  - 'playgrounds/*'
  - 'integrations'

catalog:
  '@types/node': ^22.19.17
  prettier: 3.8.3
  vite: ^8.0.10
  webpack: ^5.106.2
  lightningcss: 1.32.0
  lightningcss-darwin-arm64: 1.32.0
  lightningcss-darwin-x64: 1.32.0
  lightningcss-linux-arm64-gnu: 1.32.0
  lightningcss-linux-arm64-musl: 1.32.0
  lightningcss-linux-x64-gnu: 1.32.0
  lightningcss-linux-x64-musl: 1.32.0
  lightningcss-win32-x64-msvc: 1.32.0
