import { run, html, css } from './util/run'

it('can block classes matched literally', () => {
  let config = {
    content: [{ raw: html`<div class="font-bold uppercase"></div>` }],
    blocklist: ['uppercase'],
  }

  return run('@tailwind utilities', config).then((result) => {
    return expect(result.css).toMatchCss(css`
      .font-bold {
        font-weight: 700;
      }
    `)
  })
})

it('can block classes matching a pattern', () => {
  let config = {
    content: [{ raw: html`<div class="font-bold bg-[#f00d1e]"></div>` }],
    blocklist: [/^bg-\[[^]+\]$/],
  }

  return run('@tailwind utilities', config).then((result) => {
    return expect(result.css).toMatchCss(css`
      .font-bold {
        font-weight: 700;
      }
    `)
  })
})

it('can block classes generated by the safelist', () => {
  let config = {
    content: [{ raw: html`<div class="font-bold"></div>` }],
    safelist: [{ pattern: /^bg-red-(400|500)$/ }],
    blocklist: ['bg-red-500'],
  }

  return run('@tailwind utilities', config).then((result) => {
    return expect(result.css).toMatchCss(css`
      .bg-red-400 {
        --tw-bg-opacity: 1;
        background-color: rgb(248 113 113 / var(--tw-bg-opacity));
      }
      .font-bold {
        font-weight: 700;
      }
    `)
  })
})
