/**
 * This code modifies the `index.js` JS glue code generated by napi-rs to export the `require()`'d napi module.
 * This is needed for the native bun plugin implementation.
 */
const fs = require('fs')
const path = require('path')

const indexPath = path.join(__dirname, 'index.js')
const exportLine = '\nmodule.exports.nativeBinding = nativeBinding;\n'

fs.appendFileSync(indexPath, exportLine)

const indexDtsPath = path.join(__dirname, 'index.d.ts')
const exportDtsLine = '\nexport declare const nativeBinding: unknown;\n'

fs.appendFileSync(indexDtsPath, exportDtsLine)
