<?php

return [
    'Introduction' => [
        'What is Tailwind?' => 'what-is-tailwind',
    ],
    'Getting Started' => [
        'Installation' => 'installation',
        'Configuration' => 'configuration',
        'Colors' => 'colors',
        'Responsive Design' => 'responsive-design',
        'State Variants' => 'state-variants',
        'Adding New Utilities' => 'adding-new-utilities',
        'Extracting Components' => 'extracting-components',
        'Functions &amp; Directives' => 'functions-and-directives',
        'Controlling File Size' => 'controlling-file-size',
    ],
    'Styles' => [
        'Backgrounds' => [
            'Color' => 'background-color',
            'Position' => 'background-position',
            'Repeat' => 'background-repeat',
            'Size' => 'background-size',
            'Attachment' => 'background-attachment',
        ],
        'Borders' => [
            'Width' => 'border-width',
            'Color' => 'border-color',
            'Style' => 'border-style',
        ],
        'Border Radius' => 'border-radius',
        'Container' => 'container',
        'Display' => 'display',
        'Flexbox' => [
            'Display' => 'flexbox-display',
            'Direction' => 'flexbox-direction',
            'Wrapping' => 'flexbox-wrapping',
            'Justify Content' => 'flexbox-justify-content',
            'Align Items' => 'flexbox-align-items',
            'Align Content' => 'flexbox-align-content',
            'Align Self' => 'flexbox-align-self',
            'Flex, Grow, &amp; Shrink' => 'flexbox-flex-grow-shrink',
        ],
        'Floats' => 'floats',
        'Forms' => 'forms',
        'Interactivity' => [
            'Cursor' => 'cursor',
            'Resize' => 'resize',
            'Pointer Events' => 'pointer-events',
            'User Select' => 'user-select',
        ],
        'Lists' => 'lists',
        'Opacity' => 'opacity',
        'Overflow' => 'overflow',
        'Positioning' => 'positioning',
        'Shadows' => 'shadows',
        'Sizing' => [
            'Width' => 'width',
            'Min-Width' => 'min-width',
            'Max-Width' => 'max-width',
            'Height' => 'height',
            'Min-Height' => 'min-height',
            'Max-Height' => 'max-height',
        ],
        'Spacing' => 'spacing',
        'SVG' => 'svg',
        'Typography' => [
            'Fonts' => 'fonts',
            'Color' => 'text-color',
            'Sizing' => 'text-sizing',
            'Weight' => 'font-weight',
            'Alignment' => 'text-alignment',
            'Line Height' => 'line-height',
            'Letter Spacing' => 'letter-spacing',
            'Style &amp; Decoration' => 'text-style',
            'Whitespace &amp; Wrapping' => 'whitespace-and-wrapping',
        ],
        'Vertical Alignment' => 'vertical-alignment',
        'Visibility' => 'visibility',
        'Z-Index' => 'z-index',
    ],
    'Examples' => [
        'Alerts' => 'examples/alerts',
        'Buttons' => 'examples/buttons',
        'Cards' => 'examples/cards',
        'Forms' => 'examples/forms',
        'Grids' => 'examples/grids',
        'Navigation' => 'examples/navigation',
    ],
];
