export const corePluginList = [
  'preflight',

  'container',

  'accessibility',
  'pointerEvents',
  'visibility',
  'position',
  'inset',
  'isolation',
  'zIndex',
  'order',
  'gridColumn',
  'gridColumnStart',
  'gridColumnEnd',
  'gridRow',
  'gridRowStart',
  'gridRowEnd',
  'float',
  'clear',
  'margin',
  'boxSizing',
  'display',
  'height',
  'maxHeight',
  'minHeight',
  'width',
  'minWidth',
  'maxWidth',
  'flex',
  'flexShrink',
  'flexGrow',
  'tableLayout',
  'borderCollapse',

  'transform',
  'transformOrigin',
  'translate',
  'rotate',
  'skew',
  'scale',

  'animation',

  'cursor',
  'userSelect',
  'resize',

  'listStylePosition',
  'listStyleType',

  'appearance',
  'gridAutoColumns',
  'gridAutoFlow',
  'gridAutoRows',
  'gridTemplateColumns',
  'gridTemplateRows',
  'flexDirection',
  'flexWrap',
  'placeContent',
  'placeItems',
  'alignContent',
  'alignItems',
  'justifyContent',
  'justifyItems',
  'gap',
  'space',
  'divideWidth',
  'divideStyle',
  'divideColor',
  'divideOpacity',

  'placeSelf',
  'alignSelf',
  'justifySelf',

  'overflow',
  'overscrollBehavior',
  'textOverflow',
  'whitespace',
  'wordBreak',

  'borderRadius',
  'borderWidth',
  'borderStyle',
  'borderColor',
  'borderOpacity',

  'backgroundColor',
  'backgroundOpacity',
  'backgroundImage',
  'gradientColorStops',
  'boxDecorationBreak',
  'backgroundSize',
  'backgroundAttachment',
  'backgroundClip',
  'backgroundPosition',
  'backgroundRepeat',
  'backgroundOrigin',

  'fill',
  'stroke',
  'strokeWidth',

  'objectFit',
  'objectPosition',

  'padding',

  'textAlign',
  'verticalAlign',
  'fontFamily',
  'fontSize',
  'fontWeight',
  'textTransform',
  'fontStyle',
  'fontVariantNumeric',
  'lineHeight',
  'letterSpacing',
  'textColor',
  'textOpacity',
  'textDecoration',
  'fontSmoothing',
  'placeholderColor',
  'placeholderOpacity',

  'opacity',
  'backgroundBlendMode',
  'mixBlendMode',
  'boxShadow',
  'outline',
  'ringWidth',
  'ringColor',
  'ringOpacity',
  'ringOffsetWidth',
  'ringOffsetColor',

  'filter',
  'blur',
  'brightness',
  'contrast',
  'dropShadow',
  'grayscale',
  'hueRotate',
  'invert',
  'saturate',
  'sepia',

  'backdropFilter',
  'backdropBlur',
  'backdropBrightness',
  'backdropContrast',
  'backdropGrayscale',
  'backdropHueRotate',
  'backdropInvert',
  'backdropOpacity',
  'backdropSaturate',
  'backdropSepia',

  'transitionProperty',
  'transitionDelay',
  'transitionDuration',
  'transitionTimingFunction',
]
