module.exports = {
  breakpoints: {
    sm: '576px',
    md: '768px',
    lg: '992px',
    xl: '1200px',
  },
  colors: {
    black:          '#000000',
    grey900:        '#212b35',
    grey800:        '#404e5c',
    grey700:        '#647382',
    grey600:        '#919eab',
    grey500:        '#c5ced6',
    grey400:        '#dfe3e8',
    grey300:        '#f0f2f5',
    grey200:        '#f7f9fa',
    white:          '#ffffff',
    redDark:        '#d43633',
    red:            '#f25451',
    redLight:       '#fa8785',
    redLightest:    '#fff1f0',
    orangeDark:     '#f29500',
    orange:         '#ffb82b',
    orangeLight:    '#ffd685',
    orangeLightest: '#fff8eb',
    yellowDark:     '#ffc400',
    yellow:         '#ffe14a',
    yellowLight:    '#ffea83',
    yellowLightest: '#fffbe5',
    greenDark:      '#34ae4c',
    green:          '#57d06f',
    greenLight:     '#b1f3be',
    greenLightest:  '#eefff1',
    tealDark:       '#249e9a',
    teal:           '#4dc0b5',
    tealLight:      '#9eebe4',
    tealLightest:   '#eefffd',
    blueDark:       '#3687c8',
    blue:           '#4aa2ea',
    blueLight:      '#acdaff',
    blueLightest:   '#f1f9ff',
    indigoDark:     '#4957a5',
    indigo:         '#6574cd',
    indigoLight:    '#bcc5fb',
    indigoLightest: '#f4f5ff',
    purpleDark:     '#714cb4',
    purple:         '#976ae6',
    purpleLight:    '#ceb3ff',
    purpleLightest: '#f7f3ff',
    pinkDark:       '#d84f7d',
    pink:           '#f66d9b',
    pinkLight:      '#ffa5c3',
    pinkLightest:   '#fdf2f5',
  },
  // backgroundColors: {
  //   'light': 'white',
  //   'light-soft': 'grey-200',
  //   'light-softer': 'grey-300',
  //   'light-softest': 'grey-400',
  //   'dark': 'grey-900',
  //   'dark-soft': 'grey-800',
  //   'dark-softer': 'grey-700',
  //   'dark-softest': 'grey-600',
  //   'red-dark': 'red-dark',
  //   'red': 'red',
  //   'red-light': 'red-light',
  //   'red-lightest': 'red-lightest',
  //   'orange-dark': 'orange-dark',
  //   'orange': 'orange',
  //   'orange-light': 'orange-light',
  //   'orange-lightest': 'orange-lightest',
  //   'yellow-dark': 'yellow-dark',
  //   'yellow': 'yellow',
  //   'yellow-light': 'yellow-light',
  //   'yellow-lightest': 'yellow-lightest',
  //   'green-dark': 'green-dark',
  //   'green': 'green',
  //   'green-light': 'green-light',
  //   'green-lightest': 'green-lightest',
  //   'teal-dark': 'teal-dark',
  //   'teal': 'teal',
  //   'teal-light': 'teal-light',
  //   'teal-lightest': 'teal-lightest',
  //   'blue-dark': 'blue-dark',
  //   'blue': 'blue',
  //   'blue-light': 'blue-light',
  //   'blue-lightest': 'blue-lightest',
  //   'indigo-dark': 'indigo-dark',
  //   'indigo': 'indigo',
  //   'indigo-light': 'indigo-light',
  //   'indigo-lightest': 'indigo-lightest',
  //   'purple-dark': 'purple-dark',
  //   'purple': 'purple',
  //   'purple-light': 'purple-light',
  //   'purple-lightest': 'purple-lightest',
  //   'pink-dark': 'pink-dark',
  //   'pink': 'pink',
  //   'pink-light': 'pink-light',
  //   'pink-lightest': 'pink-lightest',
  // },
  backgroundColors: [
    'blue-dark',
    'blue',
    'blue-lightest',
    'indigo',
    'indigo-light',
    'purple',
    'purple-lightest',
    'pink-dark',
    'pink',
  ],
  // backgroundColors: {
  //   primary: 'blue',
  //   primaryDark: 'blueDark',
  //   primaryLight: 'blueLight',
  //   secondary: 'orange',
  //   secondaryDark: 'orangeDark',
  //   secondaryLight: 'orangeLight',
  // }
}
