import selectorParser from 'postcss-selector-parser'
import normalizeTailwindDirectives from './lib/normalizeTailwindDirectives'
import expandTailwindAtRules from './lib/expandTailwindAtRules'
import expandApplyAtRules from './lib/expandApplyAtRules'
import evaluateTailwindFunctions from './lib/evaluateTailwindFunctions'
import substituteScreenAtRules from './lib/substituteScreenAtRules'
import resolveDefaultsAtRules from './lib/resolveDefaultsAtRules'
import collapseAdjacentRules from './lib/collapseAdjacentRules'
import collapseDuplicateDeclarations from './lib/collapseDuplicateDeclarations'
import partitionApplyAtRules from './lib/partitionApplyAtRules'
import detectNesting from './lib/detectNesting'
import { createContext } from './lib/setupContextUtils'
import { issueFlagNotices } from './featureFlags'
import { env } from './lib/sharedState'
import { expandApplyAtRules as oxideExpandApplyAtRules } from './oxide/core/expand-apply-at-rules'

export default function processTailwindFeatures(setupContext) {
  return function (root, result) {
    let { tailwindDirectives, applyDirectives } = normalizeTailwindDirectives(root)

    if (!env.OXIDE) {
      detectNesting()(root, result)
    }

    // Partition apply rules that are found in the css
    // itself.
    partitionApplyAtRules()(root, result)

    let context = setupContext({
      tailwindDirectives,
      applyDirectives,
      registerDependency(dependency) {
        result.messages.push({
          plugin: 'tailwindcss',
          parent: result.opts.from,
          ...dependency,
        })
      },
      createContext(tailwindConfig, changedContent) {
        return createContext(tailwindConfig, changedContent, root)
      },
    })(root, result)

    if (context.tailwindConfig.separator === '-') {
      throw new Error(
        "The '-' character cannot be used as a custom separator in JIT mode due to parsing ambiguity. Please use another character like '_' instead."
      )
    }

    issueFlagNotices(context.tailwindConfig)

    expandTailwindAtRules(context)(root, result)
    // Partition apply rules that are generated by
    // addComponents, addUtilities and so on.
    partitionApplyAtRules()(root, result)
    if (env.OXIDE) {
      oxideExpandApplyAtRules(context)(root, result)
    } else {
      expandApplyAtRules(context)(root, result)
    }
    evaluateTailwindFunctions(context)(root, result)
    substituteScreenAtRules(context)(root, result)
    resolveDefaultsAtRules(context)(root, result)

    collapseAdjacentRules(context)(root, result)
    collapseDuplicateDeclarations(context)(root, result)

    // Drop :merge()
    root.walkRules((rule) => {
      if (rule.selector.includes(':merge')) {
        let selectorFunctions = new Set([':merge'])
        let ast = selectorParser().astSync(rule.selector)
        ast.walkPseudos((node) => {
          if (selectorFunctions.has(node.value)) {
            node.replaceWith(node.nodes)
          }
        })
        rule.selector = ast.toString()
      }
    })
  }
}
